In [11]:
import numpy as np

data = np.loadtxt(r"C:\Users\user\Desktop\dataset.csv", skiprows = 1,delimiter=",")
data = data.astype(int)
print(data)
print(data.shape)

[[   1   54   79 ...  122   44  137]
 [   2   56  803 ... 1177   45 1302]
 [   3   48  563 ...  833   39  923]
 ...
 [ 298   38  748 ...  877   31  920]
 [ 299   33  285 ...  376   27  407]
 [ 300   29  674 ...  933   24 1019]]
(300, 11)


In [12]:
print(data[0:10])

[[   1   54   79   52   94   49  108   46  122   44  137]
 [   2   56  803   54  928   51 1053   48 1177   45 1302]
 [   3   48  563   46  653   44  743   41  833   39  923]
 [   4   49   65   47   71   45   76   42   82   40   87]
 [   5   22  497   21  589   20  680   19  771   18  862]
 [   6   40  498   38  574   36  650   34  726   32  801]
 [   7   59   59   57   68   54   77   51   86   48   95]
 [   8   38  808   37  946   35 1084   33 1222   31 1359]
 [   9   47  290   45  323   43  356   40  389   38  422]
 [  10   32  915   31 1066   29 1217   28 1368   26 1519]]


In [6]:
for i1 in np.arange(5):
    for i2 in np.arange(5):
        for i3 in np.arange(5):
            for i4 in np.arange(5):
                for i5 in np.arange(5):
                    for i6 in np.arange(5):
                        for i7 in np.arange(5):
                            print('lol')

lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol


In [20]:
chosen_price = np.zeros(300).astype(int)
print(chosen_price)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]


In [8]:
for i in np.arange(42):
    print(i*7)

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98
105
112
119
126
133
140
147
154
161
168
175
182
189
196
203
210
217
224
231
238
245
252
259
266
273
280
287


In [14]:
def sort_optimum_6(data,base,quant,rev):
    optimum = np.zeros(6)
    hit = 1000000000000
    for i1 in np.arange(5):
        for i2 in np.arange(5):
            for i3 in np.arange(5):
                for i4 in np.arange(5):
                    for i5 in np.arange(5):
                        for i6 in np.arange(5):
                            #print(j)
                            
                            quantity = data[0,1+2*i1+1]+data[1,1+2*i2+1]+data[2,1+2*i3+1]+data[3,1+2*i4+1]+data[4,1+2*i5+1]+data[5,1+2*i6+1]
                            
                            revenue = data[0,1+2*i1]*data[0,1+2*i1+1]+data[1,1+2*i2]*data[1,1+2*i2+1]+data[2,1+2*i3]*data[2,1+2*i3+1]+data[3,1+2*i4]*data[3,1+2*i4+1]+data[4,1+2*i5]*data[4,1+2*i5+1]+data[5,1+2*i6]*data[5,1+2*i6+1]
                            #if i==1:
                            #    print(quantity,revenue)
                            if quantity>quant and revenue>rev:
                                
                                current_hit = 0
                                current_hit+=(base[0]-data[0,1+2*i1])*data[0,1+2*i1+1]+(base[1]-data[1,1+2*i2])*data[1,1+2*i2+1]+(base[2]-data[2,1+2*i3])*data[2,1+2*i3+1]+(base[3]-data[3,1+2*i4])*data[3,1+2*i4+1]+(base[4]-data[4,1+2*i5])*data[4,1+2*i5+1]+(base[5]-data[5,1+2*i6])*data[5,1+2*i6+1]
                                #print(current_hit)
                                #if i==1:
                                #    print(current_hit)
                                if current_hit<hit:
                                    hit = current_hit
                                    optimum = [i1,i2,i3,i4,i5,i6]
                                    #print(optimum)
                                    
    return optimum,hit
              
def sort_optimum_7(data,base,quant,rev):
    optimum = np.zeros(7)
    hit = 1000000000000
    for i1 in np.arange(5):
        for i2 in np.arange(5):
            for i3 in np.arange(5):
                for i4 in np.arange(5):
                    for i5 in np.arange(5):
                        for i6 in np.arange(5):
                            for i7 in np.arange(5):
                            #print(j)
                            
                                quantity = data[0,1+2*i1+1]+data[1,1+2*i2+1]+data[2,1+2*i3+1]+data[3,1+2*i4+1]+data[4,1+2*i5+1]+data[5,1+2*i6+1]+data[6,1+2*i7+1]
                            
                                revenue = data[0,1+2*i1]*data[0,1+2*i1+1]+data[1,1+2*i2]*data[1,1+2*i2+1]+data[2,1+2*i3]*data[2,1+2*i3+1]+data[3,1+2*i4]*data[3,1+2*i4+1]+data[4,1+2*i5]*data[4,1+2*i5+1]+data[5,1+2*i6]*data[5,1+2*i6+1]+data[6,1+2*i7]*data[6,1+2*i7+1]
                            #if i==1:
                            #    print(quantity,revenue)
                                if quantity>quant and revenue>rev:
                                
                                    current_hit = 0
                                    current_hit+=(base[0]-data[0,1+2*i1])*data[0,1+2*i1+1]+(base[1]-data[1,1+2*i2])*data[1,1+2*i2+1]+(base[2]-data[2,1+2*i3])*data[2,1+2*i3+1]+(base[3]-data[3,1+2*i4])*data[3,1+2*i4+1]+(base[4]-data[4,1+2*i5])*data[4,1+2*i5+1]+(base[5]-data[5,1+2*i6])*data[5,1+2*i6+1]+(base[6]-data[6,1+2*i7])*data[6,1+2*i7+1]
                                #print(current_hit)
                                #if i==1:
                                #    print(current_hit)
                                    if current_hit<hit:
                                        hit = current_hit
                                        optimum = [i1,i2,i3,i4,i5,i6,i7]
                                    #print(optimum)
                                    
    return optimum,hit
                                

In [80]:
optimum,hit = sort_optimum(data[0:6],data[0:6,1],3609,127138)

In [81]:
print(optimum)

[1, 2, 2, 0, 4, 4]


In [88]:
base_price = data[:,1]
chosen_price = np.zeros(300).astype(int)
hit=0
total_min = 0
for i in np.arange(50):
    #print(i)
    total_min+=int(sum(data[6*i:6*(i+1),2])*1.25)+1
    optimum = sort_optimum(data[6*i:6*(i+1)],base_price[6*i:6*(i+1)],int(sum(data[6*i:6*(i+1),2])*1.25)+1,int(sum(data[6*i:6*(i+1),1]*data[6*i:6*(i+1),2])*1.10)+1)
    #print(optimum)
    chosen_price[6*i:6*(i+1)]=np.array(optimum[0])
    #print(chosen_price[6*i:6*(i+1)].shape,np.array(optimum[0]).shape)
    hit+=optimum[1]

In [15]:
base_price = data[:,1]
chosen_price = np.zeros(300).astype(int)
hit=0
total_min = 0
for i in np.arange(42):
    optimum = sort_optimum_7(data[7*i:7*(i+1)],base_price[7*i:7*(i+1)],int(sum(data[7*i:7*(i+1),2])*1.20)+1,int(sum(data[7*i:7*(i+1),1]*data[7*i:7*(i+1),2])*1.07)+1)
    chosen_price[7*i:7*(i+1)]=np.array(optimum[0])
    hit+=optimum[1]
    
optimum = sort_optimum_6(data[294:300],base_price[294:300],int(sum(data[294:300,2])*1.20)+1,int(sum(data[294:300,1]*data[294:300,2])*1.07)+1)
chosen_price[294:300]=np.array(optimum[0])
hit+=optimum[1]

#for i in np.arange(50):
   # total_min+=int(sum(data[6*i:6*(i+1),2])*1.25)+1
  #  optimum = sort_optimum(data[6*i:6*(i+1)],base_price[6*i:6*(i+1)],int(sum(data[6*i:6*(i+1),2])*1.25)+1,int(sum(data[6*i:6*(i+1),1]*data[6*i:6*(i+1),2])*1.10)+1)

  #  chosen_price[6*i:6*(i+1)]=np.array(optimum[0])
  
 #   hit+=optimum[1]

In [16]:
print(chosen_price)
print(total_min)

[1 1 0 0 4 0 1 1 0 1 2 1 1 2 0 2 1 0 4 0 4 2 3 0 2 0 2 0 0 1 1 3 1 3 0 1 1
 4 0 0 0 0 1 2 4 0 1 1 0 1 0 3 0 3 3 2 0 1 4 1 3 1 2 1 3 0 4 0 2 0 0 1 2 1
 2 2 1 1 2 1 1 4 0 1 4 3 1 0 2 4 4 1 1 1 1 4 2 0 2 2 1 1 0 1 2 1 0 3 0 1 0
 1 0 3 4 0 1 0 4 1 2 4 2 1 0 0 3 1 0 2 2 4 3 2 1 1 3 0 0 1 2 3 1 0 1 4 0 0
 1 1 2 2 1 2 1 0 4 0 0 0 1 0 2 1 1 1 3 3 2 1 1 3 1 1 0 3 0 2 3 1 0 2 0 0 3
 0 0 1 4 1 2 2 0 1 0 3 1 1 2 2 2 2 0 0 2 0 2 0 0 4 1 3 1 3 0 0 2 4 3 0 1 4
 1 1 2 2 0 0 4 1 2 0 0 2 1 3 1 4 0 2 1 3 0 0 1 4 1 0 0 1 4 0 1 3 0 2 0 1 1
 2 0 2 0 0 2 0 2 1 1 0 0 4 0 0 2 0 0 2 1 3 2 1 0 2 2 2 4 1 2 0 3 0 1 3 4 1
 2 1 2 2]
0


In [17]:
revenue_final=0
quantity_final=0

for i in np.arange(300):
    revenue_final+=data[i,1+2*chosen_price[i]]*data[i,1+2*chosen_price[i]+1]
    quantity_final+=data[i,1+2*chosen_price[i]+1]
    
print(revenue_final,quantity_final)

6398415 173448


In [18]:
final_hit = 0
for i in np.arange(300):
    final_hit+=(base_price[i]-data[i,1+2*chosen_price[i]])*data[i,1+2*chosen_price[i]+1]
print(final_hit)

390638


In [39]:
print(list(chosen_price))

[0, 1, 1, 0, 4, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [110]:
print(np.array([1,2,3,4,5]),np.array([1,2,3,4,5])+1)

[1 2 3 4 5] [2 3 4 5 6]


In [23]:
base_price = data[:,1]
chosen_price = np.zeros(300).astype(int)
hit=0
total_min = 0
for i in np.arange(1):
    optimum = sort_optimum_7(data[7*i:7*(i+1)],base_price[7*i:7*(i+1)],int(sum(data[7*i:7*(i+1),2])*1.25)+1,int(sum(data[7*i:7*(i+1),1]*data[7*i:7*(i+1),2])*1.10)+1)
    chosen_price[7*i:7*(i+1)]=np.array(optimum[0])
    hit+=optimum[1]

In [36]:
for i in np.arange(7,300):
    min_hit = 100000000
    for j in np.arange(5):
        hit = 0
        revenue_final=0
        quantity_final=0
        for k in np.arange(i):
            hit+=(base_price[k]-data[k,1+2*chosen_price[k]])*data[k,1+2*chosen_price[k]+1]
            revenue_final+=data[k,1+2*chosen_price[k]]*data[k,1+2*chosen_price[k]+1]
            quantity_final+=data[k,1+2*chosen_price[k]+1]
        hit+=(base_price[i]-data[i,1+2*j])*data[i,1+2*j+1]
        revenue_final+=data[i,1+2*j]*data[i,1+2*j+1]
        quantity_final+=data[i,1+2*j+1]
        print(hit)
        if quantity_final>1.10*sum(data[0:i+1,2]) and revenue_final>1.25*sum(data[0:i+1,2]*data[0:i+1,1]):
            if hit<min_hit:
                chosen_price[i]=j
                min_hit = hit

7758
8704
11010
13868
17271
7758
8404
9182
10481
11556
7758
8824
11409
13230
16872
7758
8050
8775
9693
10362
7758
7916
8256
8623
9025
7758
8800
10086
11616
14798
7758
8722
10000
11592
13498
7758
8062
8402
8778
9369
7758
8126
8564
9072
9646
7758
8393
9828
11483
13365
7758
8138
8570
9048
9582
7758
8643
9744
12162
13803
7758
9768
13173
15885
20138
7758
7850
7966
8109
8274
7758
8165
8668
9766
10508
7758
8222
9324
10078
11586
7758
8448
9290
10284
11430
7758
8451
10089
12063
14373
7758
7988
8393
8878
9430
7758
9772
12290
15312
18838
7758
9450
12368
14744
18508
7758
9386
11174
14009
16155
7758
8582
10593
13083
16060
7758
9288
11282
13746
16670
7758
8403
9996
11150
13452
7758
8511
10230
12233
14520
7758
8445
9302
10329
12468
7758
8152
8588
9066
9586
7758
8896
11053
13750
16987
7758
7916
8110
8334
8703
7758
8670
9852
11304
13026
7758
9302
11050
13008
15166
7758
8804
10030
11436
13022
7758
8263
9399
10703
11550
7758
8212
8790
9486
10310
7758
8367
9696
11173
12798
7758
9914
13968
18998
25017
7758

In [40]:
def check_optimum(trol):
    min_hit = 10000000000000
    for j in np.arange(5):
        hit = 0
        revenue_final=0
        quantity_final=0
        for i in np.arange(len(trol)):
            hit+=(base_price[i]-data[i,1+2*chosen_price[i]])*data[i,1+2*chosen_price[i]+1]
            revenue_final+=data[i,1+2*chosen_price[i]]*data[i,1+2*chosen_price[i]+1]
            quantity_final+=data[i,1+2*chosen_price[i]+1]
        hit+=(base_price[len(trol)]-data[len(trol),1+2*j])*data[len(trol),1+2*j+1]
        revenue_final+=data[len(trol),1+2*j]*data[len(trol),1+2*j+1]
        quantity_final+=data[len(trol),1+2*j+1]
        print(quantity_final,1.10*sum(data[0:len(trol)+1,2]))
        if quantity_final>1.10*sum(data[0:i+1,2]) and revenue_final>1.25*sum(data[0:i+1,2]*data[0:len(trol)+1,1]):
            if hit<min_hit:
                chosen_price[len(trol)]=j
                min_hit = hit
        
for i in np.arange(7,300):
    check_optimum(chosen_price[0:i])

3279 2820.4
3288 2820.4
3297 2820.4
3306 2820.4
3315 2820.4
4836 3709.2000000000003
4974 3709.2000000000003
5112 3709.2000000000003
5250 3709.2000000000003
5387 3709.2000000000003
4608 4028.2000000000003
4641 4028.2000000000003
4674 4028.2000000000003
4707 4028.2000000000003
4740 4028.2000000000003
6148 5034.700000000001
6299 5034.700000000001
6450 5034.700000000001
6601 5034.700000000001
6752 5034.700000000001
5769 5303.1
5817 5303.1
5864 5303.1
5912 5303.1
5959 5303.1
5825 5468.1
5833 5468.1
5841 5468.1
5848 5468.1
5856 5468.1
7515 6480.1
7637 6480.1
7759 6480.1
7881 6480.1
8003 6480.1
8207 7366.700000000001
8365 7366.700000000001
8522 7366.700000000001
8679 7366.700000000001
8836 7366.700000000001
7685 7522.900000000001
7695 7522.900000000001
7704 7522.900000000001
7713 7522.900000000001
7722 7522.900000000001
8209 7889.200000000001
8244 7889.200000000001
8279 7889.200000000001
8314 7889.200000000001
8348 7889.200000000001
9034 8526.1
9090 8526.1
9145 8526.1
9200 8526.1
9256 8526.1


53750 58045.9
53784 58045.9
54053 58364.9
54088 58364.9
54122 58364.9
54156 58364.9
54190 58364.9
54873 58975.4
54960 58975.4
55047 58975.4
55133 58975.4
55220 58975.4
54662 59164.600000000006
54676 59164.600000000006
54689 59164.600000000006
54702 59164.600000000006
54715 59164.600000000006
54820 59346.100000000006
54841 59346.100000000006
54861 59346.100000000006
54881 59346.100000000006
54901 59346.100000000006
54785 59417.600000000006
54798 59417.600000000006
54811 59417.600000000006
54823 59417.600000000006
54836 59417.600000000006
56272 60271.200000000004
56368 60271.200000000004
56463 60271.200000000004
56558 60271.200000000004
56654 60271.200000000004
57042 61121.50000000001
57150 61121.50000000001
57258 61121.50000000001
57365 61121.50000000001
57473 61121.50000000001
57911 62024.600000000006
57967 62024.600000000006
58023 62024.600000000006
58079 62024.600000000006
58135 62024.600000000006
58790 62959.600000000006
58894 62959.600000000006
58997 62959.600000000006
59101 62959.

110504 119790.00000000001
110630 119790.00000000001
110756 119790.00000000001
110618 120347.70000000001
110670 120347.70000000001
110721 120347.70000000001
110773 120347.70000000001
110824 120347.70000000001
110923 120794.3
110984 120794.3
111044 120794.3
111104 120794.3
111165 120794.3
111005 121062.70000000001
111037 121062.70000000001
111069 121062.70000000001
111101 121062.70000000001
111132 121062.70000000001
112515 122027.40000000001
112646 122027.40000000001
112776 122027.40000000001
112906 122027.40000000001
113036 122027.40000000001
111780 122105.50000000001
111794 122105.50000000001
111807 122105.50000000001
111820 122105.50000000001
111833 122105.50000000001
112931 122777.6
112981 122777.6
113030 122777.6
113079 122777.6
113128 122777.6
113542 123449.70000000001
113576 123449.70000000001
113610 123449.70000000001
113643 123449.70000000001
113677 123449.70000000001
114829 124493.6
114943 124493.6
115057 124493.6
115170 124493.6
115284 124493.6
114158 124646.50000000001
114182

In [59]:
array = [1, 1, 0, 0, 4, 0, 1, 1, 0, 1, 2, 1, 1, 2, 0, 2, 1, 0, 4, 0, 4, 2, 3, 0, 2, 0, 2, 0, 0, 1, 1, 3, 1, 3, 0, 1, 1, 4, 0, 0, 0, 0, 1, 2, 4, 0, 1, 1, 0, 1, 0, 3, 0, 3, 3, 2, 0, 1, 4, 1, 3, 1, 2, 1, 3, 0, 4, 0, 2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 4, 0, 1, 4, 3, 1, 0, 2, 4, 4, 1, 1, 1, 1, 4, 2, 0, 2, 2, 1, 1, 0, 1, 2, 1, 0, 3, 0, 1, 0, 1, 0, 3, 4, 0, 1, 0, 4, 1, 2, 4, 2, 1, 0, 0, 3, 1, 0, 2, 2, 4, 3, 2, 1, 1, 3, 0, 0, 1, 2, 3, 1, 0, 1, 4, 0, 0, 1, 1, 2, 2, 1, 2, 1, 0, 4, 0, 0, 0, 1, 0, 2, 1, 1, 1, 3, 3, 2, 1, 1, 3, 1, 1, 0, 3, 0, 2, 3, 1, 0, 2, 0, 0, 3, 0, 0, 1, 4, 1, 2, 2, 0, 1, 0, 3, 1, 1, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 4, 1, 3, 1, 3, 0, 0, 2, 4, 3, 0, 1, 4, 1, 1, 2, 2, 0, 0, 4, 1, 2, 0, 0, 2, 1, 3, 1, 4, 0, 2, 1, 3, 0, 0, 1, 4, 1, 0, 0, 1, 4, 0, 1, 3, 0, 2, 0, 1, 1, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 0, 0, 4, 0, 0, 2, 0, 0, 2, 1, 3, 2, 1, 0, 2, 2, 2, 4, 1, 2, 0, 3, 0, 1, 3, 4, 1, 2, 1, 2, 2]

In [60]:
print(array)

[1, 1, 0, 0, 4, 0, 1, 1, 0, 1, 2, 1, 1, 2, 0, 2, 1, 0, 4, 0, 4, 2, 3, 0, 2, 0, 2, 0, 0, 1, 1, 3, 1, 3, 0, 1, 1, 4, 0, 0, 0, 0, 1, 2, 4, 0, 1, 1, 0, 1, 0, 3, 0, 3, 3, 2, 0, 1, 4, 1, 3, 1, 2, 1, 3, 0, 4, 0, 2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 4, 0, 1, 4, 3, 1, 0, 2, 4, 4, 1, 1, 1, 1, 4, 2, 0, 2, 2, 1, 1, 0, 1, 2, 1, 0, 3, 0, 1, 0, 1, 0, 3, 4, 0, 1, 0, 4, 1, 2, 4, 2, 1, 0, 0, 3, 1, 0, 2, 2, 4, 3, 2, 1, 1, 3, 0, 0, 1, 2, 3, 1, 0, 1, 4, 0, 0, 1, 1, 2, 2, 1, 2, 1, 0, 4, 0, 0, 0, 1, 0, 2, 1, 1, 1, 3, 3, 2, 1, 1, 3, 1, 1, 0, 3, 0, 2, 3, 1, 0, 2, 0, 0, 3, 0, 0, 1, 4, 1, 2, 2, 0, 1, 0, 3, 1, 1, 2, 2, 2, 2, 0, 0, 2, 0, 2, 0, 0, 4, 1, 3, 1, 3, 0, 0, 2, 4, 3, 0, 1, 4, 1, 1, 2, 2, 0, 0, 4, 1, 2, 0, 0, 2, 1, 3, 1, 4, 0, 2, 1, 3, 0, 0, 1, 4, 1, 0, 0, 1, 4, 0, 1, 3, 0, 2, 0, 1, 1, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 0, 0, 4, 0, 0, 2, 0, 0, 2, 1, 3, 2, 1, 0, 2, 2, 2, 4, 1, 2, 0, 3, 0, 1, 3, 4, 1, 2, 1, 2, 2]


In [61]:
formatted = list()
formatted.append([0,0])
for i in np.arange(300):
    if array[i]==0:
        formatted.append([i+1,"Base_Price"])
    else:
        formatted.append([i+1,"Price"+str(array[i])])

In [62]:
print(formatted)

[[0, 0], [1, 'Price1'], [2, 'Price1'], [3, 'Base_Price'], [4, 'Base_Price'], [5, 'Price4'], [6, 'Base_Price'], [7, 'Price1'], [8, 'Price1'], [9, 'Base_Price'], [10, 'Price1'], [11, 'Price2'], [12, 'Price1'], [13, 'Price1'], [14, 'Price2'], [15, 'Base_Price'], [16, 'Price2'], [17, 'Price1'], [18, 'Base_Price'], [19, 'Price4'], [20, 'Base_Price'], [21, 'Price4'], [22, 'Price2'], [23, 'Price3'], [24, 'Base_Price'], [25, 'Price2'], [26, 'Base_Price'], [27, 'Price2'], [28, 'Base_Price'], [29, 'Base_Price'], [30, 'Price1'], [31, 'Price1'], [32, 'Price3'], [33, 'Price1'], [34, 'Price3'], [35, 'Base_Price'], [36, 'Price1'], [37, 'Price1'], [38, 'Price4'], [39, 'Base_Price'], [40, 'Base_Price'], [41, 'Base_Price'], [42, 'Base_Price'], [43, 'Price1'], [44, 'Price2'], [45, 'Price4'], [46, 'Base_Price'], [47, 'Price1'], [48, 'Price1'], [49, 'Base_Price'], [50, 'Price1'], [51, 'Base_Price'], [52, 'Price3'], [53, 'Base_Price'], [54, 'Price3'], [55, 'Price3'], [56, 'Price2'], [57, 'Base_Price'], [58,

In [63]:
data = np.savetxt(r"C:\Users\user\Desktop\critereon3.csv",formatted,delimiter=",",fmt='%s')